name: Backend Type Check, Linting & Formatting

on:
  pull_request:
    paths:
      - spotify/*.py
      - tests/*.py
      - pyproject.toml
      - main.py
      - .github/workflows/backend_linting.yaml

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set uv & Install Dependencies
        uses: ./.github/actions/uv-setup
      - name: Run ruff check
        run: uv run ruff check --no-cache --config ./pyproject.toml

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set uv & Install Dependencies
        uses: ./.github/actions/uv-setup
      - name: Run ruff format
        run: uv run ruff format --check --no-cache --config ./pyproject.toml

  type-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set uv & Install Dependencies
        uses: ./.github/actions/uv-setup
      - name: Run type checking
        run: uv run ty check

  tests:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
      - type-checking
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: not_a_real_user
          MONGO_INITDB_ROOT_PASSWORD: not_a_real_password
          MONGO_INITDB_DATABASE: spotify_randomness
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set uv & Install Dependencies
        uses: ./.github/actions/uv-setup
      - name: Run Tests
        env:
          MONGO_INITDB_ROOT_USERNAME: not_a_real_user
          MONGO_INITDB_ROOT_PASSWORD: not_a_real_password
          MONGO_INITDB_DATABASE: spotify_randomness
        run: uv run pytest --disable-warnings
